import Head from 'next/head';

export default function Home() {
  const targetClassName = 'important';

  const focusHandler = (event) => {
    //to stop event propagation
    event.stopPropagation();

    const parent = document.getElementById('john');
    const childs = parent?.children || [];

    for (let i = 0; i < childs.length; i++) {
      var childElement = childs[i];
      if (childElement.classList.contains(targetClassName)) {
        childElement.classList.add('shape');
      }
    }
  };

  return (
    <>
      <Head>
        <title>Kennect Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <div id="john">
          <input id="name" type="text" onFocus={focusHandler} />
          {/* <p>
          color of these divs will be changed to darkgrey after focusing on
          input element, because class - 'shape', will get added to them.
        </p> */}
          <div className="important">Div with class important</div>
          <div className="important">Div with class important</div>
          <div className="important">Div with class important</div>
          {/* <p>
          Since below divs do not have class - 'important', the class - 'shape'
          was not added to them and their background color didn't change.
        </p> */}
          <div> Div without class important </div>
          <div> Div without class important </div>
        </div>
      </div>
    </>
  );
}
